### PR TITLE
Update advanced-layouts.md

### PR DESCRIPTION
**Pull request by centaur1**

### CODE REVIEW

**Comment by rvagg** [comment]
@warpfork I think this doc is yours? maybe you want to find some better wording than this, "in a phrase" doesn't really work.

Thanks for picking this up @centaur1!

**Comment by centaur1** [comment]
Perhaps just:
"In short,"

**Comment by rvagg** [comment]
yeah, that sounds better

**Comment by warpfork** [comment]
Okay, I took your commit, but amended it to use "in short" :)

It's now on master (and you still get the credit, in github's eyes).  (Because I amended the commit, the hash is different, and github doesn't recognize it as related to this PR, so I have to close it now.  But your change was accepted :))

**Pull request closed without merging**
